// GERADO a partir da prateleira de fundos da XP, capturada em 2026-09-22.
// 146 fundos, 32 deles com ticker em bolsa.
//
// Guardamos só o que é estável: nome comercial, ticker e quantidade mínima. Preço unitário,
// quantidade disponível, deságio e rentabilidade mudam todo dia — embuti-los seria carregar
// dado vencido dentro de um sistema cuja regra é não inventar dado. A quantidade mínima entra
// como AVISO e nunca como bloqueio, justamente porque também pode mudar.
//
// Para atualizar: copie a lista do portal e rode `npm run fundos:update -- arquivo.txt`.

export const CAPTURADO_EM = '2026-09-22';

export const FUNDOS_XP = [
  { nome: "XP CDI 99 FOF Private Jun/27 FII RL", ticker: null, qtdMinima: "2.500.000" },
  { nome: "XP CDI 98 FOF Private Jun/27 FII RL", ticker: null, qtdMinima: "1.000.000" },
  { nome: "XP CDI 98 FOF Private Dez/27 FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "XP CDI 98 FOF Private Nov/26 FII RL", ticker: null, qtdMinima: "500.000" },
  { nome: "XP CDI 97 CRI Private Ago/27 FII RL", ticker: null, qtdMinima: "250.000" },
  { nome: "XP CDI 97 Return FIDC RL", ticker: null, qtdMinima: "100.000" },
  { nome: "XP CDI 96 FOF Unique Dez/27 FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "XP CDI 96 FOF Unique Nov/26 FII RL", ticker: null, qtdMinima: "100.000" },
  { nome: "XP CDI 96 CRI Unique Ago/27 FII RL", ticker: null, qtdMinima: "100.000" },
  { nome: "XP CDI 96 Return FIDC RL", ticker: null, qtdMinima: "10.000" },
  { nome: "XP CDI 94 FOF Jun/27 FII RL", ticker: null, qtdMinima: "50.000" },
  { nome: "XP CDI 94 CRI Jun/27 FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "XP CDI 94 CRI Ago/27 FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "XP CDI 93 FOF Nov/26 FII RL", ticker: null, qtdMinima: "10.000" },
  { nome: "XP CDI 93 FOF Dez/27 FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "XP CDI 92 CRI Ago/27 FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "AZ Quest Debêntures Incentivadas 01/2032 FIC FI-Infra RL", ticker: null, qtdMinima: "1.000" },
  { nome: "AZ Quest Debêntures Incentivadas 01/2033 FIC FI-Infra RL", ticker: null, qtdMinima: "500" },
  { nome: "TG Renda Imobiliária Feeder Pré FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "TG Renda Imobiliária Sênior A", ticker: "TGRI11", qtdMinima: "10" },
  { nome: "AZ Quest Luna - FIAgro", ticker: "AZQA11", qtdMinima: "10" },
  { nome: "TG Renda Imobiliária Feeder FII RL", ticker: "TGRI", qtdMinima: "10" },
  { nome: "XP Private Equity II - Classe A - FIP Multiestratégia", ticker: null, qtdMinima: "25.000" },
  { nome: "TG Eurogarden Feeder FII RL", ticker: null, qtdMinima: "500" },
  { nome: "RBR Infra DI Renda Mais FI Infra RF RL", ticker: null, qtdMinima: "100" },
  { nome: "XP Selection Alternativo FIP Multi - Classe A", ticker: null, qtdMinima: "10.000" },
  { nome: "TG Renda Urbana Feeder FII RL", ticker: null, qtdMinima: "100" },
  { nome: "AZ Quest Panorama Renda Sênior Feeder FII RL", ticker: null, qtdMinima: "500" },
  { nome: "Newave Energia FIP - Classe D (com DI)", ticker: null, qtdMinima: "10.900" },
  { nome: "Maua Lajes Corporativas Feeder FII RL - Senior", ticker: null, qtdMinima: "1.000" },
  { nome: "Valora Infra Dívida FIP IE", ticker: "VGIE11", qtdMinima: "10" },
  { nome: "LCP Prefixado II Feeder FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Jive Dist & Spec Sits IV Adv Qual II FicFim CP - Modelo A", ticker: null, qtdMinima: "10.000" },
  { nome: "Legacy Capital Portfolio Renda Mais FI-INFRA RF LP RL", ticker: null, qtdMinima: "100" },
  { nome: "AZ-AXS Energia FIP-IE RL - Subclasse Sênior A1", ticker: null, qtdMinima: "100" },
  { nome: "SPX CRI Portfolio Renda Mais", ticker: null, qtdMinima: "100" },
  { nome: "Riza Renda Imobiliária Feeder FII RL - Subclasse I", ticker: null, qtdMinima: "500" },
  { nome: "JiveMauá BossaNova Crédito Securitizado FIDC - Cota Sênior", ticker: null, qtdMinima: "100" },
  { nome: "XP Hedge Fund", ticker: "XPHF11", qtdMinima: "10" },
  { nome: "XP SS 1 FIC FIDC RL-NP", ticker: null, qtdMinima: "100.380" },
  { nome: "Valora CRI CDI D 180 FII RL - Subclasse A", ticker: null, qtdMinima: "500" },
  { nome: "TG Real Estate", ticker: "TGRE11", qtdMinima: "10" },
  { nome: "Root Capital Figueira FIDC de Responsab Limit", ticker: null, qtdMinima: "100" },
  { nome: "Riza Viseu FII RL - Subclasse A", ticker: null, qtdMinima: "1.000" },
  { nome: "Franklin BSP Crédito Estruturado Global I FIF MM IE RL", ticker: null, qtdMinima: "1.000" },
  { nome: "ARZ Bridge Inv Real Estate Credit FIM IE CP RL", ticker: null, qtdMinima: "500" },
  { nome: "Bocaina Infra DI Renda", ticker: null, qtdMinima: "500" },
  { nome: "XP Infra V FIP IE RL - Subclasse A", ticker: null, qtdMinima: "10.000" },
  { nome: "Mauá Capital Logística Feeder FII - RL", ticker: null, qtdMinima: "10" },
  { nome: "Riza Terrax Vintage FIAgro RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Vinci Crédito Portfólio CDI+ FIDC", ticker: null, qtdMinima: "100" },
  { nome: "VBI Crédito", ticker: "AVBI11", qtdMinima: "10" },
  { nome: "JiveMauá Bossanova Crédito Securitizado (Varejo) FIDC RL", ticker: null, qtdMinima: "100" },
  { nome: "Kijani Asatala FIAgro", ticker: "KJNT11", qtdMinima: "10" },
  { nome: "Wings Renda Imobiliária Feeder FII - RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Valora Infra Pré Titanium FIP-IE RL", ticker: null, qtdMinima: "500" },
  { nome: "Augme XPCE I FIDC RL – Subclasse A", ticker: null, qtdMinima: "500" },
  { nome: "XP Logístico Prime Yield II FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Hedge Crédito CDI Renda Mais FII", ticker: null, qtdMinima: "1.000" },
  { nome: "Valora Agro Pré I Fiagro RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Artesanal CDI + FIDC III RL - Sênior", ticker: null, qtdMinima: "1.000" },
  { nome: "AZ Quest Panorama Renda CDI FI Responsabilidade Limitada", ticker: null, qtdMinima: "1.000" },
  { nome: "BTG Pactual Prime Logística FII RL - Subclasse A", ticker: "BTLP11", qtdMinima: "500" },
  { nome: "Valora CRI CDI Renda+ FII RL", ticker: null, qtdMinima: "100" },
  { nome: "Leste Real Estate Pré Advisory FIF MM CP IE RL - Subclasse Senior", ticker: null, qtdMinima: "500" },
  { nome: "Jivemauá Bossanova Crédito Securitizado II FIDC RL - Subclasse Sênior", ticker: null, qtdMinima: "1.000" },
  { nome: "Arz Confidas Dwight Real Estate Crédit Pós-Fixado FIF Multimercado CP RL", ticker: null, qtdMinima: "5.000" },
  { nome: "BGR Galpões Logísticos I Feeder FII", ticker: null, qtdMinima: "1.000" },
  { nome: "Vinci MAV IV FIAgro FIC RL", ticker: null, qtdMinima: "500" },
  { nome: "Brio Renda Mais FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "ARZ Alpine Bain Capital Private Credit II FIC FIM CP RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Manatí Recebíveis Estruturados", ticker: "MARE11", qtdMinima: "10" },
  { nome: "XP Credit Opportunities FIDC - Modelo A", ticker: null, qtdMinima: "10.038" },
  { nome: "Cyrela Hedge Fund FII RL", ticker: "CYHF11", qtdMinima: "10" },
  { nome: "Alianza Crédito Renda Mais Feeder FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "XP Infra IV FIP IE - Classe A", ticker: null, qtdMinima: "10.000" },
  { nome: "Mauá Capital Crédito Estruturado", ticker: "MCCE11", qtdMinima: "100" },
  { nome: "Augme Crédito Estruturado FII RL", ticker: "AUGM11", qtdMinima: "10" },
  { nome: "JiveMauá Agronegócio FIC FIAgro RL", ticker: null, qtdMinima: "500" },
  { nome: "Navi Infra FIP-IE (RL)", ticker: "NFIP11", qtdMinima: "10" },
  { nome: "Valora Imobiliário Multiestratégia Premium", ticker: "VGPR11", qtdMinima: "10" },
  { nome: "Manatí Renda CDI FII RL", ticker: null, qtdMinima: "100" },
  { nome: "RBR Renda Fixa CDI+ FII RL", ticker: null, qtdMinima: "500" },
  { nome: "SPX Private Equity I Advisory FIP Multi - Classe A", ticker: null, qtdMinima: "25.000" },
  { nome: "XP Special Opportunities FIP Multi - Classe A", ticker: null, qtdMinima: "25.859" },
  { nome: "RBR Infra Advisory Pré III Renda+ FIP-IE", ticker: null, qtdMinima: "500" },
  { nome: "LCP Renda Imobiliária Feeder FII", ticker: null, qtdMinima: "100" },
  { nome: "Occam Portfolio Crédito FIDC RL", ticker: null, qtdMinima: "100" },
  { nome: "XP Habitat Renda Imobiliária II Feeder FII RL", ticker: null, qtdMinima: "500" },
  { nome: "Solis Portfolio Crédito CDI+ FIC FIDC RL", ticker: null, qtdMinima: "100" },
  { nome: "XP CDI CRI I FII RL - Mezanino I", ticker: null, qtdMinima: "50.000" },
  { nome: "MNH Private Income FIF MM IE - RL", ticker: null, qtdMinima: "5.000" },
  { nome: "Verde A&I Portfolio Renda Mais FII RL", ticker: null, qtdMinima: "100" },
  { nome: "AZ Quest Renda Mais Infra-Yield VI FIP-IE", ticker: null, qtdMinima: "100" },
  { nome: "Capitânia Agro Crédito", ticker: "CPAC11", qtdMinima: "10" },
  { nome: "XP Private Equity I FIP Multi - Classe A", ticker: null, qtdMinima: "50.000" },
  { nome: "XP IdeaZarvos", ticker: "IDZA11", qtdMinima: "10.000" },
  { nome: "XP Crédito Agro", ticker: "XPAG11", qtdMinima: "10" },
  { nome: "XP Habitat FII", ticker: "XPHB11", qtdMinima: "10" },
  { nome: "Triplo A Residencial FII RL", ticker: null, qtdMinima: "5.000" },
  { nome: "Pátria Infra Energia Core Renda FIP INFRA", ticker: "PIER11", qtdMinima: "100" },
  { nome: "Mauá Capital Crédito Liquidez 180 FII RL- Subclasse A", ticker: null, qtdMinima: "500" },
  { nome: "Verde A&I Cedro II Portfolio Renda FII RL", ticker: null, qtdMinima: "500" },
  { nome: "HSI Renda CDI Crédito Estruturado FII RL", ticker: null, qtdMinima: "500" },
  { nome: "AZ Quest Panorama Data Centers FII RL", ticker: null, qtdMinima: "500" },
  { nome: "Navi Residencial Prime Opportunities - Classe C - FII Resp L", ticker: null, qtdMinima: "50.000" },
  { nome: "XP Habitat Renda Imobiliária Feeder FII", ticker: null, qtdMinima: "100" },
  { nome: "Jive Dist & Spec Sits IV Adv Qual III FicFim CP - Modelo A", ticker: null, qtdMinima: "10.000" },
  { nome: "Valora CRI Pré I Feeder I FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Kinea PE V Feeder Advisory FIP Multi RL - Classe A", ticker: null, qtdMinima: "25.000" },
  { nome: "Vinci Capital Partners IV - Classe A - Advisory FIP Multiest", ticker: null, qtdMinima: "10.000" },
  { nome: "AZ Quest Panorama Crédito Imob.", ticker: "AZPR11", qtdMinima: "10" },
  { nome: "Capitânia Yield Sênior FIC FIDC RL - Subclasse Sênior", ticker: null, qtdMinima: "1.000" },
  { nome: "Exa Renda High Grade FII", ticker: null, qtdMinima: "100" },
  { nome: "Arz Confidas Dwight Real Estate Crédit Pré FIF Multimercado - CP RL", ticker: null, qtdMinima: "5.000" },
  { nome: "Valora Infra Renda Mais FIP IE RL Subclasse Sênior", ticker: null, qtdMinima: "1.000" },
  { nome: "XP Agro Renda Feeder Fiagro RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Jive Dist & Spec Sits IV Adv Qual FicFim CP - Modelo A", ticker: null, qtdMinima: "10.000" },
  { nome: "RBR Infra Crédito FIC INFRA RF", ticker: "RBRJ11", qtdMinima: "100" },
  { nome: "Riza Malls Feeder FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Vinci Crédito FIAgro", ticker: "VICA11", qtdMinima: "10" },
  { nome: "JGP Ecossistema Infra CDI CP RL", ticker: "JGFA11", qtdMinima: "10" },
  { nome: "BTG Log AAA Cajamar FII RL - Subclasse Sênior", ticker: null, qtdMinima: "1.000" },
  { nome: "AZ Quest Infra Yield FIP IE", ticker: "AZQI11", qtdMinima: "10" },
  { nome: "Capitânia Hedge Fund FII RL", ticker: "CPHF11", qtdMinima: "10" },
  { nome: "Cix MCMV Feeder FII RL", ticker: null, qtdMinima: "500" },
  { nome: "XP Office Prime FII RL", ticker: null, qtdMinima: "500" },
  { nome: "LCP Prefixado Feeder FII", ticker: null, qtdMinima: "100" },
  { nome: "Jivemaua Bossanova Credito Securitizado II (Varejo) FIDC RL", ticker: null, qtdMinima: "1.000" },
  { nome: "JHSF Capital Malls Feeder FII RL", ticker: null, qtdMinima: "1.000" },
  { nome: "JGP Crédito Agro", ticker: "JGPT11", qtdMinima: "10" },
  { nome: "Navi Hedge Fund", ticker: "IMOV11", qtdMinima: "10" },
  { nome: "ARX FII Portfólio Renda CDI+ RL", ticker: null, qtdMinima: "100" },
  { nome: "XP Logístico Prime Yield FII - I FII RL", ticker: null, qtdMinima: "10" },
  { nome: "Manatí Renda CDI Plus FII RL", ticker: null, qtdMinima: "500" },
  { nome: "Sparta Pré 2028 FI-Infra RF CP RL", ticker: null, qtdMinima: "1.000" },
  { nome: "XP Renda Imobiliária Feeder FII RL", ticker: null, qtdMinima: "10" },
  { nome: "Riza Domus FII", ticker: "RZDS11", qtdMinima: "10" },
  { nome: "JGP Infra", ticker: "JGPI11", qtdMinima: "10" },
  { nome: "Pátria PE VII Advisory FIP Multi - Classe A", ticker: null, qtdMinima: "10.000" },
  { nome: "XP Multi Renda FII RL", ticker: "MRFA11", qtdMinima: "10" },
  { nome: "Pátria Crédito Agrícola FiAgro", ticker: "PAAG11", qtdMinima: "10" },
  { nome: "Blueoak SS I Feeder FIC FIP - Subclasse A - Multiestratégia RL", ticker: null, qtdMinima: "10.000" },
  { nome: "Itaú Crédito Estruturado Advisory Alpes III FIDC RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Pátria Infraestrutura Crédito DI III FIP-IE RL", ticker: null, qtdMinima: "1.000" },
  { nome: "Newave Energia I Advisory – Classe A - FIP Multiestratégia", ticker: null, qtdMinima: "10.000" }
];
